

const TermsOfServicePage = () => {
  return (
    <div className="max-w-4xl mx-auto py-20 px-6 text-brand-text">
      <div className="text-center mb-16">
        <h1 className="text-5xl font-bold font-heading text-brand-primary mb-4">Terms of Service</h1>
        <p className="text-xl text-brand-text/70 italic font-heading">Effective Date: June 2026</p>
      </div>

      <div className="bg-brand-surface p-12 rounded-3xl border border-brand-primary/10 shadow-sm space-y-12">
        
        <section className="bg-red-50 border-l-4 border-red-800 p-6 rounded-r-xl mb-12">
          <h2 className="text-2xl font-bold text-red-800 font-heading mb-3">URGENT MEDICAL DISCLAIMER</h2>
          <p className="text-lg text-red-900 leading-relaxed font-semibold">
            MedClear is NOT for medical emergencies. If you are experiencing a medical emergency, please dial 911 or visit the nearest emergency room immediately. MedClear is a financial navigation tool, not a clinical triage service.
          </p>
        </section>

        <section>
          <h2 className="text-3xl font-bold text-brand-primary font-heading mb-4">1. Not Medical Advice / No Doctor-Patient Relationship</h2>
          <p className="text-lg leading-relaxed text-brand-text/90 mb-4">
            The MedClear platform and its underlying Artificial Intelligence models provide information strictly for **informational and financial navigational purposes only**. 
          </p>
          <p className="text-lg leading-relaxed text-brand-text/90">
            Using MedClear does not create a doctor-patient relationship, nor does it establish a fiduciary relationship between you and MedClear or any hospital entity. None of the outputs generated by MedClear constitute professional medical advice, clinical diagnosis, or legal counsel.
          </p>
        </section>

        <section>
          <h2 className="text-3xl font-bold text-brand-primary font-heading mb-4">2. AI-Specific Limitations and Probabilistic Output</h2>
          <p className="text-lg leading-relaxed text-brand-text/90 mb-4">
            While MedClear utilizes state-of-the-art Large Language Models (LLMs) backed by a Verifiable Retrieval-Augmented Generation (RAG) pipeline to ensure accuracy, AI is inherently probabilistic.
          </p>
          <ul className="list-disc pl-6 space-y-3 text-lg text-brand-text/90">
            <li><strong>Disclaimer of Absolute Accuracy:</strong> MedClear does not guarantee the accuracy, completeness, or timeliness of AI-generated insights. Hospital policies are subject to unannounced changes.</li>
            <li><strong>"Human-in-the-Loop" Requirement:</strong> You must verify the AI-generated quotes against the official hospital documentation provided by the platform before making any financial or legal decisions.</li>
            <li><strong>Assumption of Risk:</strong> By using MedClear, you assume full responsibility for any decisions made based on the app’s output.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-3xl font-bold text-brand-primary font-heading mb-4">3. Limitation of Liability</h2>
          <p className="text-lg leading-relaxed text-brand-text/90 mb-4">
            <strong>"As Is" Clause:</strong> The MedClear service is provided on an "as is" and "as available" basis. We expressly disclaim all warranties, whether express or implied, including but not limited to the implied warranties of merchantability and fitness for a particular purpose.
          </p>
          <p className="text-lg leading-relaxed text-brand-text/90 mb-4">
            <strong>Liability Cap:</strong> To the maximum extent permitted by applicable law, in no event shall MedClear, its affiliates, or its licensors be liable for any indirect, punitive, incidental, special, or consequential damages arising out of or in any way connected with the use of this service.
          </p>
          <p className="text-lg leading-relaxed text-brand-text/90">
            <strong>Indemnification:</strong> You agree to indemnify, defend, and hold harmless MedClear from any claims, liabilities, or demands arising from your misuse of the platform or your reliance on its outputs in lieu of professional legal or financial advice.
          </p>
        </section>

        <section>
          <h2 className="text-3xl font-bold text-brand-primary font-heading mb-4">4. Third-Party Integrations</h2>
          <p className="text-lg leading-relaxed text-brand-text/90">
            MedClear integrates with third-party hospitals' public domains and AI infrastructure providers. MedClear is not responsible for the performance, security, or downtime of these third-party services, nor do we claim affiliation with the hospitals indexed in our database.
          </p>
        </section>

      </div>
    </div>
  );
};

export default TermsOfServicePage;
